<img src="images/QISKit-c copy.gif" alt="Note: In order for images to show up in this jupyter notebook you need to select File => Trusted Notebook" width="250 px" align="left">

# Hadamard Action: Approach 2
## Jupyter Notebook 2/3 for the Teach Me QISKIT Tutorial Competition
- Connor Fieweger

<img src="images/hadamard_action.png" alt="Note: In order for images to show up in this jupyter notebook you need to select File => Trusted Notebook" width="750 px" align="left">

Another approach to showing equivalence of the presented circuit diagrams is to represent the operators on the qubits as matrices and the qubit states as column vectors. The output is found by applying the matrix that represents the action of the circuit onto the initial state column vector to find the final state column vector. Since the numpy library already enables making linear algebra computations such as these, we'll use that to employ classical programming in order to understand this quantum circuit.

In [1]:
import numpy as np

## Circuit i)
For i), the initial state of the input is represented by the tensor product of the two input qubits in the initial register. This is given by:

$$\Psi = \psi_1 \otimes \psi_2$$

Where each $\psi$ can be either 0 or 1

This results in the following input states for $\Psi$: |00>, |01>, |10>, or |11>. Represented by column vectors, these are:

$$\text{|00>} = \left(\begin{array}{c}
        1 \\
        0 \\
        0 \\
        0
\end{array}\right)$$
$$\text{|01>} = \left(\begin{array}{c}
        0 \\
        1 \\
        0 \\
        0
\end{array}\right)$$
$$\text{|10>} = \left(\begin{array}{c}
        0 \\
        0 \\
        1 \\
        0
\end{array}\right)$$
$$\text{|11>} = \left(\begin{array}{c}
        0 \\
        0 \\
        0 \\
        1
\end{array}\right)$$


In [2]:
# These column vectors can be stored in numpy arrays so that we can operate 
# on them with the circuit diagram's corresponding matrix (which is to be evaluated)
# as follows:
zero_zero = np.array([[1],[0],[0],[0]])
zero_one = np.array([[0],[1],[0],[0]])
one_zero = np.array([[0],[0],[1],[0]])
one_one = np.array([[0],[0],[0],[1]])
Psi = {'zero_zero': zero_zero, 'zero_one': zero_one, 'one_zero': one_zero, 'one_one': one_one}
# ^We can conveniently store all possible input states in a dictionary and then print to check the representations:
for key, val in Psi.items():
    print(key, ':', '\n', val)

one_zero : 
 [[0]
 [0]
 [1]
 [0]]
zero_zero : 
 [[1]
 [0]
 [0]
 [0]]
zero_one : 
 [[0]
 [1]
 [0]
 [0]]
one_one : 
 [[0]
 [0]
 [0]
 [1]]


The action of the circuit gates on this state is simply the CNOT operator. For a control qubit on line 1 and a subject qubit on line 2, CNOT is given by the 4x4 matrix (as discussed in the appendix notebook): 

$$CNOT_1 = \left[\begin{array}{cccc}
        1 & 0 & 0 & 0 \\
        0 & 1 & 0 & 0 \\
        0 & 0 & 0 & 1 \\
        0 & 0 & 1 & 0
\end{array}\right]$$

This matrix is the operator that describes the effect of the circuit on the initial state. By taking $CNOT_1$|$\Psi$> = |$\Psi$'>, then, the final state for i) can be found.

In [3]:
# storing CNOT as a numpy array:
CNOT_1 = np.matrix([[1, 0, 0, 0],[0, 1, 0, 0],[0, 0, 0, 1],[0, 0, 1, 0]])
print(CNOT_1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [4]:
print('FINAL STATE OF i):')
#Apply CNOT to each possible state for |Psi> to find --> |Psi'>
for key, val in Psi.items():
    print(key, 'becomes..\n', CNOT_1*val)

FINAL STATE OF i):
one_zero becomes..
 [[0]
 [0]
 [0]
 [1]]
zero_zero becomes..
 [[1]
 [0]
 [0]
 [0]]
zero_one becomes..
 [[0]
 [1]
 [0]
 [0]]
one_one becomes..
 [[0]
 [0]
 [1]
 [0]]


As one can see, the first set of two states (00, 01) has stayed the same, while the second (10, 11) has flipped to (11, 10). This is readily understood when considering the defining logic of the CNOT gate - the subject qubit on line 2 is flipped if the control qubit on line 1 in the state |1> (this is also referred to as the control qubit being 'on'). Summatively, then, the action of i) is given by: [|00>,|01>,|10>,|11>] --> [|00>,|01>,|11>,|10>].

## Circuit ii)
For ii), a similar examination of the input states and the result when the circuit operation matrix is applied to these states can be done. The input states are the same as those in i), so we can just use the variable 'Psi' that we stored earlier. In order to find the matrix representation of the circuit, a little more depth in considering the matrix that represents the gates is required as follows: 

First, consider the parallel application of the Hadamard gate 'H' to each wire. In order to represent this as an operator on the two-qubit-tensor-space state ('$\Psi$'), one needs to take the tensor product of the single-qubit-space's ('$\psi$') Hadamard with itself: $H \otimes H = H^{\otimes 2}$

As discussed in the appendix notebook, this is given by:
$$\text{H}^{\otimes 2} = \frac{1}{2}\left[\begin{array}{cccc}
        1 & 1 & 1 & 1 \\
        1 & -1 & 1 & -1 \\
        1 & 1 & -1 & -1 \\
        1 & -1 & -1 & 1
\end{array}\right]$$

This is then the first matrix to consider when finding the matrix that represents the action of circuit ii).

In [5]:
# storing this in a numpy array:
H_2 = .5*np.matrix([[1, 1, 1, 1],[1, -1, 1, -1],[1, 1, -1, -1],[1, -1, -1, 1]])
print('H_2:')
print(H_2)

H_2:
[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


The next operation on the qubits is a CNOT controlled by line 2. This is given by the 4x4 matrix (also in the appendix notebook): 

$$CNOT_2 = \left[\begin{array}{cccc}
        1 & 0 & 0 & 0 \\
        0 & 0 & 0 & 1 \\
        0 & 0 & 1 & 0 \\
        0 & 1 & 0 & 0
\end{array}\right]$$

This is then the second matrix to consider in finding the matrix that represents the action of circuit ii).

In [6]:
# storing this in a numpy array:
CNOT_2 = np.matrix([[1, 0, 0, 0],[0, 0, 0, 1],[0, 0, 1, 0],[0, 1, 0, 0]])

Finally, the set of parallel hadamard matrices as given by $H^{\otimes 2}$ is again applied to the two-qubit-space. With this, all matrices that contribute to the circuit's action have been found. Applying each operator to the state as one reads the circuit diagram from left to right, one finds: $(H^{\otimes 2})(CNOT_2)(H^{\otimes} 2)\Psi$ = $\Psi$ '. The $(H^{\otimes 2})(CNOT_2)(H^{\otimes} 2)$ term can be evaluated through matrix multiplication to a single 4x4 matrix that represents the entire circuit as an operator, let's call it 'A'.

In [7]:
A = H_2*CNOT_2*H_2

In [8]:
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


This representation should look familiar, no? 

In [9]:
print(CNOT_1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


Just to double check,;

In [10]:
for key, val in Psi.items():
    print(key, 'becomes...\n', A*val)

one_zero becomes...
 [[0.]
 [0.]
 [0.]
 [1.]]
zero_zero becomes...
 [[1.]
 [0.]
 [0.]
 [0.]]
zero_one becomes...
 [[0.]
 [1.]
 [0.]
 [0.]]
one_one becomes...
 [[0.]
 [0.]
 [1.]
 [0.]]


The action of i) and ii) are evidently the same then $\square$.